Make command succeed always
Signed-off-by: Theofilos Manitaras <manitart@cscs.ch>

diff --git a/ci/cpe.yml b/ci/cpe.yml
--- a/ci/cpe.yml
+++ b/ci/cpe.yml
@@ -16,7 +16,9 @@ run rfm_test:
     - source venv_reframe_cpe/bin/activate
     - pip install reframe-hpc
     - | 
-      changedtests=( $(git diff origin/alps...HEAD --name-only --oneline --no-merges | grep -e '^checks/.*\.py') )
+
+      # Use || true so that the following command does return exit code
+      changedtests=( $(git diff origin/alps...HEAD --name-only --oneline --no-merges | grep -e '^checks/.*\.py' || true) )
 
       if [ ${#changedtests[@]} -ne 0 ]; then
           changedtests_path=""
